### PR TITLE
[#4] Inroduce Timestamp and functions

### LINKED ISSUE #4: Implement 'Timestamp' and 'TimeDiff' numerics
Proposed by @int-index:

1. `Timestamp` — can be negative, has no units
2. `Time` (`TimeDiff`) — cannot be negative, has units

- [x] `timeDiff :: KnownRat unit => Timestamp -> Timestamp -> (Ordering, Time unit)`
- [x] `timeAdd :: KnownRat unit => Time unit -> Time unit -> Time unit`
- [x] `timeMul :: KnownRat unit => Ratio Natural -> Time unit -> Time unit`
- [x] `timeDiv :: KnownRat unit => Time unit -> Time unit -> Ratio Natural`

### LINKED ISSUE #14: Remove the 'Num' instance for 'Time'
`(*) :: Time unit -> Time unit -> Time unit` is an incorrect type, this is not how units work. If you multiply seconds by seconds, you have seconds squared, not seconds.

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #4 
Resolves #14 (`Num` and  `Fraction` instances are rewritten manually with `error` on `*` and `/` operators)

### CODE REVIEW

File: src/Time/Timestamp.hs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+       , timeDiv
+       ) where
+
+import GHC.Real (denominator, numerator, (%))
+
+import Time.Rational (KnownRat, RatioNat)
+import Time.Units (Time (..))
+
+-- | Similar to 'Time' but has no units and can be negative.
+newtype Timestamp = Timestamp Rational
```
Comment (ChShersh) [inline src/Time/Timestamp.hs]: What do you think about names `TimeStamp` and `TimeDiff`?
If we rename `Time` to `TimeDiff` it's better to have `TimeStamp` for consistency, I guess. Maybe there's sense in renaming `Time` into `TimeDiff`.

File: src/Time/Timestamp.hs [hunk 2]
```diff
@@ -0,0 +1,42 @@
+{-# LANGUAGE GeneralizedNewtypeDeriving #-}
+{-# LANGUAGE Rank2Types                 #-}
```
Comment (ChShersh) [inline src/Time/Timestamp.hs]: `Rank2Types` extension looks redundant to me, but I'm not sure...

File: src/Time/Timestamp.hs [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+    deriving (Show, Read, Num, Eq, Ord, Enum, Fractional, Real, RealFrac)
+
+
+-- | Returns the result of comparison of two 'Timestamp's and
+-- the 'Time' of that difference of given time unit.
+timeDiff :: KnownRat unit => Timestamp -> Timestamp -> (Ordering, Time unit)
+timeDiff (Timestamp a) (Timestamp b) =
+    let order         = compare a b
+        dif           = abs (a - b)
+        t :: RatioNat = fromIntegral (numerator dif) % fromIntegral (denominator dif)
```
Comment (ChShersh) [inline src/Time/Timestamp.hs]: `dif` is already normalized because `(-)` operator for `Rational` performs normalization. So you can use just `(:%)` here.

File: src/Time/Timestamp.hs [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+newtype Timestamp = Timestamp Rational
+    deriving (Show, Read, Num, Eq, Ord, Enum, Fractional, Real, RealFrac)
+
+
+-- | Returns the result of comparison of two 'Timestamp's and
+-- the 'Time' of that difference of given time unit.
+timeDiff :: KnownRat unit => Timestamp -> Timestamp -> (Ordering, Time unit)
+timeDiff (Timestamp a) (Timestamp b) =
+    let order         = compare a b
+        dif           = abs (a - b)
```
Comment (int-index) [inline src/Time/Timestamp.hs]: Let's not have `abs` here, I was thinking about something like this:

```
let
  order = compare a b
  d = case order of
    EQ -> 0
    LT -> a - b
    GT -> b - a
in
  (order, d)
```

File: src/Time/Timestamp.hs [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+        t :: RatioNat = fromIntegral (numerator dif) % fromIntegral (denominator dif)
+    in (order, Time t)
+
+-- | Returns the result of addition of two 'Time' elements.
+timeAdd :: KnownRat unit => Time unit -> Time unit -> Time unit
+timeAdd = (+)
```
Comment (int-index) [inline src/Time/Timestamp.hs]: How did you manage to use `(+)` here? Time *most definitely* cannot have a `Num` instance.

Comment (int-index) [reply src/Time/Timestamp.hs]: https://github.com/serokell/o-clock/issues/14

Comment (ChShersh) [reply src/Time/Timestamp.hs]: Personally, I'm okay with `Num` instance for `Time`. You can write `(3 :: Second) + 5` without problems. Also you can write `(5 :: Second) - 3`. If you out of range while subtracting, when `Natural` will throw exception. Not the perfect behavior, but still might be convenient, if you use it carefully.

`(3 :: Second) * (5 :: Second)` probably doesn't make sense from physics point of view. But let's user decide what they want: more convenient interface with `(*)` or more type-safe with `timeAdd`. Also, having `Num` instances allows us to have other numeric instances with `floor` functions which are useful in real life.

Comment (int-index) [reply src/Time/Timestamp.hs]: `(3 :: Second) * (5 :: Second)` is ridiculous and no sane library for units would allow this.

Comment (int-index) [reply src/Time/Timestamp.hs]: if you insist on having a `Num` instance for numeric literals, make multiplication and division throw an error.

Comment (ChShersh) [reply src/Time/Timestamp.hs]: `time-units` allows this. And we never had problems with it (because we never used `*` for time units). It's just the `Num` hierarchy which is not perfect. Unfortunately, we can't have everything from `Num` except `(*)`. But the rest of `Num` looks really useful and convenient. So ¯\_(ツ)_/¯.

Having `error` inside `(*)` and `(/)` operators is okay to me.

File: src/Time/Units.hs [hunk 6]
```diff
@@ -74,7 +74,7 @@ import Time.Rational (type (%), type (**), type (//), type (:%), DivRat, KnownRa
 import qualified Control.Concurrent as Concurrent
 
 newtype Time (rat :: Rat) = Time RatioNat
```
Comment (ChShersh) [inline src/Time/Units.hs]: Maybe we can also add record field for `Time` constructor? Like

```haskell
newtype Time (rat :: Rat) = Time { unTime :: RatioNat }
```
What do you think? Sometimes can be convenient to write functions in point-free style.

File: src/Time/Units.hs [hunk 7]
```diff
@@ -136,6 +136,18 @@ instance KnownSymbol (ShowUnit unit) => Read (Time unit) where
             unless (timeUnitStr == symbolVal (Proxy @(ShowUnit unit))) pfail
             pure $ Time (n % m)
 
+instance Num (Time unit) where
+    (Time t1) + (Time t2) = Time (t1 + t2)
```
Comment (ChShersh) [inline src/Time/Units.hs]: Maybe you can add `{-# INLINE #-}` pragmas. Also you can implement all methods (except `error` ones) by delegating to `coerce` function how it's done here:

* https://hackage.haskell.org/package/base-4.10.1.0/docs/src/Data.Semigroup.html#line-243

So, this should work I guess.

```haskell
(+) = coerce ((+) :: RatioNat -> RatioNat -> RatioNat)
```

File: src/Time/Units.hs [hunk 8]
```diff
@@ -136,6 +136,18 @@ instance KnownSymbol (ShowUnit unit) => Read (Time unit) where
             unless (timeUnitStr == symbolVal (Proxy @(ShowUnit unit))) pfail
             pure $ Time (n % m)
 
+instance Num (Time unit) where
```
Comment (ChShersh) [inline src/Time/Units.hs]: I think you can also add Haddock documentation to these manual instances. Like, say, that they behave just like derived ones, except `(*)` operator throws runtime error with `error`.
